version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
#  front:
#    image: node:14.15.3
#    volumes:
#      - ./frontend:/work/frontend
#    ports:
#      - "3000:3000"
#    command: npm start
#    environment:
#      - NODE_ENV=developmentn
#
#  front_web:
#    build:
#      context: .
#      dockerfile: ./infra/docker/front_web/Dockerfile
#    volumes:
#      - ./frontend/public:/work/frontend/public
#      - ./infra/docker/front_web/default.conf:/etc/nginx/default.conf
#    ports:
#      - "80:80"
#
  api:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}

  api_web:
    build:
      context: .
      dockerfile: ./infra/docker/api_nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./backend:/work/backend

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
